### PR TITLE
Fix scripts

### LINKED ISSUE #277: Scripts aren't re-generating tables
**Describe the bug**

Scripts should be auto-generating format tables, including things like TNG. They should be failing right now since TNG isn't there. They aren't running.

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #277 

Due to #275 this should fail CI ~~and RTD~~

### CODE REVIEW

File: doc/source/scripts/generate_all.sh [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e  # exit on failure
```
Comment (lilyminium) [inline doc/source/scripts/generate_all.sh:3]: This is the most important part of the PR -- we exit the docs build if the scripts fail, which they will do if entries such as TNG are missing.

**Comment by lilyminium** [comment]
This PR breaks CI on purpose -- if no one reviews or has comments, I'll merge in a few hours in anticipation of #275.
